latent_dims: 64
num_epochs: 1
batch_size: 100
capacity: 64
learning_rate: 1e-3
weight_decay: 1e-5
zsize: 64

use_gpu: True

TRAIN_SET: 'sets/Large_Var_Hight.csv'
VAL_SET: 'sets/Small_Var_Hight.csv'
VAL_SET_TWO: 'sets/7_Var_Hight.csv'

log_file: 'test_terminal_output.txt'

TRAIN: True
