latent_dims: 64
num_epochs: 120
batch_size: 64
capacity: 64
learning_rate: 1e-3
weight_decay: 1e-5
zsize: 64

use_gpu: True

TRAIN_SET: '../data/sets/train.csv'
VAL_SET: '../data/sets/val.csv'
VAL_SET_TWO: '../data/sets/test.csv'

log_file: 'DEPTH_terminal_output_wandb.txt'

Name: 'DEPTH_WANDB'

TRAIN: True
